# fly.toml app configuration file generated for jadoo on 2025-07-05T02:27:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jadoo'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
app = "npm start" # or the command that starts your Express server
worker = "node dist/queue.js"
